version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: streaming
    ports:
      - "5430:5432"
    volumes:
      - /home/gwdcks/Faculdade/PIM\ VIII/DockerImages/DockerVolumes/pgdata:/var/lib/postgresql/data

